
# Record types of surfaces
surfaces = {
    0: "bunker",
    1: "green",
    2: "fairway",
    3: "rough",
    4: "heavyrough",
    5: "clearobjects",
    6: "cleartrees",
    7: "surface1",
    8: "surface2",
    9: "water",
    10: "surface3"
}

featuresToSurfaces = {
    "bunker": 0,
    "green": 1,
    "fairway": 2,
    "rough": 3,
    "heavyrough": 4,
    "clearobjects": 5,
    "cleartrees": 6,
    "surface1": 7,
    "surface2": 8,
    "water": 9,
    "surface3": 10,
    "cartpath": 10,
}

# 12 medium_oval
# 15 medium_square
# 35 blob
brushes = {
    8: "firm_circle",
    9: "medium_circle",
    10: "soft_circle",
    15: "soft_square",
    54: "very_soft_circle",
    72: "hard_square",
    73: "hard_circle"
}

themes = {
    2: "desert",
    5: "boreal",
    6: "tropical",
    7: "countryside",
    8: "harvest",
    9: "winter",
    10: "delta",
    11: "rustic",
    12: "swiss",
    13: "steppe",
    14: "autumn",
    15: "highlands",
    50: "temperate",
    54: "fjordland"
}

normal_trees = {
    2: [0, 1, 2, 3, 9],
    5: [0, 1],
    6: [0, 1, 2, 3, 4, 5, 6, 7],
    7: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16],
    8: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    9: [],
    10: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 12],
    11: [0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    12: [0, 1, 3, 4, 7, 8, 10],
    13: [0, 1, 2, 3, 4, 5, 6, 7],
    14: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    15: [0, 1, 6, 7],
    50: []
}

skinny_trees = {
    2: [10, 11, 12, 13, 14, 15, 16],
    5: [3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16],
    6: [8, 9, 13, 14, 15, 16, 17, 18, 19],
    7: [13, 14],
    8: [0, 1, 2],
    9: [],
    10: [],
    11: [13, 14, 16],
    12: [2, 5, 9],
    13: [8, 9, 10, 11, 12, 13, 14, 15],
    14: [12, 15],
    15: [2, 3, 8, 9, 10, 22],
    50: []
}

tee_colors = {
    4: "red",
    0: "green",
    3: "white",
    2: "blue",
    1: "black",
    5: "gold"
}

version_tags = {
    19: {
        'tees' : 'teePositions',
        'pins' : 'pinPositions',
        'holes' : 'holes',
        'crowd' : 'crowdLocations',
        'splines' : 'surfaceSplines',
        'surfaces' : 'surfaces',
        'oob' : 'outOfBounds',
        'objects' : 'placedObjects2',
        'file_encoding' : 'utf-16'
    },
    23: {
        'tees' : 'teePositions',
        'pins' : 'pins',
        'holes' : 'holes2',
        'crowd' : 'crowdLocations',
        'splines' : 'surfaceSplines2',
        'surfaces' : 'surfaces',
        'oob' : 'outOfBounds',
        'objects' : 'placedObjects3',
        'file_encoding' : 'utf-16-le'
    },
    25: {
        'tees' : 'tees',
        'pins' : 'pins',
        'holes' : 'holes3',
        'crowd' : 'crowdMap2',
        'splines' : 'surfaceSplines2',
        'surfaces' : 'surfaceBrushes',
        'oob' : 'outOfBounds2',
        'objects' : 'placedObjects4',
        'file_encoding' : 'utf-16-le'
    }
}

#-------------------------------
# 2k trees

trees_2k = [
    "Assets/Foliage/SpeedTree/Trees/Afghan/Prefabs/AfghanDeadTree1",
    "Assets/Foliage/SpeedTree/Trees/Afghan/Prefabs/AfghanDeadTree2",
    "Assets/Foliage/SpeedTree/Trees/Afghan/Prefabs/AfghanDeadTree3",
    "Assets/Foliage/SpeedTree/Trees/Afghan/Prefabs/AfghanTree1A",
    "Assets/Foliage/SpeedTree/Trees/Afghan/Prefabs/AfghanTree1B",
    "Assets/Foliage/SpeedTree/Trees/Afghan/Prefabs/AfghanTree2",
    "Assets/Foliage/SpeedTree/Trees/Afghan/Prefabs/AfghanTree8",
    "Assets/Foliage/SpeedTree/Trees/Afghan/Prefabs/AfghanTree9A",
    "Assets/Foliage/SpeedTree/Trees/Afghan/Prefabs/AfghanTree9B",
    "Assets/Foliage/SpeedTree/Trees/Alaska_Cedar/Prefabs/AlaskaCedar_Desktop01",
    "Assets/Foliage/SpeedTree/Trees/Alaska_Cedar/Prefabs/AlaskaCedar_Desktop02",
    "Assets/Foliage/SpeedTree/Trees/Alaska_Cedar/Prefabs/AlaskaCedar_Desktop_Bare01",
    "Assets/Foliage/SpeedTree/Trees/Alaska_Cedar/Prefabs/AlaskaCedar_Desktop_Bare02",
    "Assets/Foliage/SpeedTree/Trees/Alaska_Cedar/Prefabs/AlaskaCedar_Desktop_Bare03",
    "Assets/Foliage/SpeedTree/Trees/Alaska_Cedar/Prefabs/AlaskaCedar_Desktop_Bare04",
    "Assets/Foliage/SpeedTree/Trees/American_Elm/Prefabs/American_Elm_Desktop01",
    "Assets/Foliage/SpeedTree/Trees/American_Elm/Prefabs/American_Elm_Desktop02",
    "Assets/Foliage/SpeedTree/Trees/American_Elm/Prefabs/American_Elm_Desktop03",
    "Assets/Foliage/SpeedTree/Trees/American_Elm/Prefabs/American_Elm_Desktop_FallA01",
    "Assets/Foliage/SpeedTree/Trees/American_Elm/Prefabs/American_Elm_Desktop_FallA02",
    "Assets/Foliage/SpeedTree/Trees/American_Elm/Prefabs/American_Elm_Desktop_FallB01",
    "Assets/Foliage/SpeedTree/Trees/American_Sycamore/Prefabs/American_Sycamore_Desktop01",
    "Assets/Foliage/SpeedTree/Trees/American_Sycamore/Prefabs/American_Sycamore_Desktop02",
    "Assets/Foliage/SpeedTree/Trees/American_Sycamore/Prefabs/American_Sycamore_Desktop_FallA01", 
    "Assets/Foliage/SpeedTree/Trees/American_Sycamore/Prefabs/American_Sycamore_Desktop_FallA02",
    "Assets/Foliage/SpeedTree/Trees/CedarTrees/Prefabs/CedarTree1",
    "Assets/Foliage/SpeedTree/Trees/CedarTrees/Prefabs/CedarTree2",
    "Assets/Foliage/SpeedTree/Trees/CedarTrees/Prefabs/CedarTree3",
    "Assets/Foliage/SpeedTree/Trees/Coconut_Palm/Prefabs/CoconutPalmTree1",
    "Assets/Foliage/SpeedTree/Trees/Coconut_Palm/Prefabs/CoconutPalmTree2",
    "Assets/Foliage/SpeedTree/Trees/Coconut_Palm/Prefabs/CoconutPalmTree4",
    "Assets/Foliage/SpeedTree/Trees/Coconut_Palm/Prefabs/CoconutPalmTree5",
    "Assets/Foliage/SpeedTree/Trees/Coconut_Palm/Prefabs/CoconutPalmTree6",
    "Assets/Foliage/SpeedTree/Trees/Coconut_Palm/Prefabs/CoconutPalmTree7",
    "Assets/Foliage/SpeedTree/Trees/Coconut_Palm/Prefabs/CoconutPalmTree9",
    "Assets/Foliage/SpeedTree/Trees/Coconut_Palm/Prefabs/CoconutPalmTree10",
    "Assets/Foliage/SpeedTree/Trees/Coconut_Palm/Prefabs/CoconutPalmTree11",
    "Assets/Foliage/SpeedTree/Trees/Coconut_Palm/Prefabs/CoconutPalmTree12",
    "Assets/Foliage/SpeedTree/Trees/Douglas_Fir/Prefabs/DouglasFir_Desktop01",
    "Assets/Foliage/SpeedTree/Trees/Douglas_Fir/Prefabs/DouglasFir_Desktop02",
    "Assets/Foliage/SpeedTree/Trees/Douglas_Fir/Prefabs/DouglasFir_Desktop03",
    "Assets/Foliage/SpeedTree/Trees/Eastern_White_Pine/Prefabs/Eastern_White_Pine_Desktop01",
    "Assets/Foliage/SpeedTree/Trees/Eastern_White_Pine/Prefabs/Eastern_White_Pine_Desktop02",
    "Assets/Foliage/SpeedTree/Trees/Eastern_White_Pine/Prefabs/Eastern_White_Pine_Desktop03",
    "Assets/Foliage/SpeedTree/Trees/European_Aspen/Prefabs/European_Aspen_Desktop_FallA01",
    "Assets/Foliage/SpeedTree/Trees/European_Aspen/Prefabs/European_Aspen_Desktop_FallA02",
    "Assets/Foliage/SpeedTree/Trees/European_Aspen/Prefabs/European_Aspen_Desktop_FallB01",
    "Assets/Foliage/SpeedTree/Trees/European_White_Birch/Prefabs/European_White_Birch_Desktop01",
    "Assets/Foliage/SpeedTree/Trees/European_White_Birch/Prefabs/European_White_Birch_Desktop02",
    "Assets/Foliage/SpeedTree/Trees/European_White_Birch/Prefabs/European_White_Birch_Desktop03",
    "Assets/Foliage/SpeedTree/Trees/European_White_Birch/Prefabs/European_White_Birch_Desktop04",
    "Assets/Foliage/SpeedTree/Trees/European_White_Birch/Prefabs/European_White_Birch_Desktop05",
    "Assets/Foliage/SpeedTree/Trees/European_White_Birch/Prefabs/European_White_Birch_Desktop_FallA01",
    "Assets/Foliage/SpeedTree/Trees/European_White_Birch/Prefabs/European_White_Birch_Desktop_FallA02",
    "Assets/Foliage/SpeedTree/Trees/European_White_Birch/Prefabs/European_White_Birch_Desktop_FallB01",
    "Assets/Foliage/SpeedTree/Trees/Generic_Conifer/Prefabs/Generic_Conifer_Desktop01",
    "Assets/Foliage/SpeedTree/Trees/Generic_Conifer/Prefabs/Generic_Conifer_Desktop02",
    "Assets/Foliage/SpeedTree/Trees/Generic_Conifer/Prefabs/Generic_Conifer_Desktop03",
    "Assets/Foliage/SpeedTree/Trees/Generic_Conifer/Prefabs/Generic_Conifer_Desktop04",
    "Assets/Foliage/SpeedTree/Trees/Generic_Conifer/Prefabs/Generic_Conifer_Desktop05",
    "Assets/Foliage/SpeedTree/Trees/Generic_Conifer/Prefabs/Generic_Conifer_Desktop06",
    "Assets/Foliage/SpeedTree/Trees/Green_Ash/Prefabs/Green_Ash_Desktop_101",
    "Assets/Foliage/SpeedTree/Trees/Green_Ash/Prefabs/Green_Ash_Desktop_102",
    "Assets/Foliage/SpeedTree/Trees/Green_Ash/Prefabs/Green_Ash_Desktop_103",
    "Assets/Foliage/SpeedTree/Trees/Green_Ash/Prefabs/Green_Ash_Desktop_104",
    "Assets/Foliage/SpeedTree/Trees/Green_Ash/Prefabs/Green_Ash_Desktop_2_Fall01",
    "Assets/Foliage/SpeedTree/Trees/Green_Ash/Prefabs/Green_Ash_Desktop_FallA02",
    "Assets/Foliage/SpeedTree/Trees/Lombardy_Poplar/Prefabs/Lombardy_Poplar_Desktop_Fall01",
    "Assets/Foliage/SpeedTree/Trees/Lombardy_Poplar/Prefabs/Lombardy_Poplar_Desktop_Fall02",
    "Assets/Foliage/SpeedTree/Trees/Lombardy_Poplar/Prefabs/Lombardy_Popular_Desktop01",
    "Assets/Foliage/SpeedTree/Trees/Lombardy_Poplar/Prefabs/Lombardy_Popular_Desktop02",
    "Assets/Foliage/SpeedTree/Trees/London_Plane/Prefabs/London_Plane_Desktop_Fall01",
    "Assets/Foliage/SpeedTree/Trees/London_Plane/Prefabs/London_Plane_Desktop_Fall02",
    "Assets/Foliage/SpeedTree/Trees/Red_Maple/Prefabs/Red_Maple_Desktop01",
    "Assets/Foliage/SpeedTree/Trees/Red_Maple/Prefabs/Red_Maple_Desktop_Fall01",
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop01",
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop02",
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop03",
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop04",
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop05",
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop06",
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop11", 
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop21",
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop22", 
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop23", 
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop24",
    "Assets/Foliage/SpeedTree/Trees/Scots_Pine/Prefabs/ScotsPine_Desktop25",
    "Assets/Foliage/SpeedTree/Trees/Southern_Live_Oak/Prefabs/SouthernLiveOak_Desktop_Bare01",
    "Assets/Foliage/SpeedTree/Trees/Southern_Live_Oak/Prefabs/SouthernLiveOak_Desktop_Bare02",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree1A",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree1B",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree1C",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree1E",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree2A",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree2B",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree2C",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree2D",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree3A",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree3B",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree4A",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree4B",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree4C",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree5A",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/JungleTree5B",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree1A",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree1B",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree1C",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree1D",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree2A",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree2B",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree2C",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree2D",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree3B",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree3D",
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree4B", 
    "Assets/Foliage/SpeedTree/Trees/TropicalTrees/Prefabs/PalmTree4C",
    "Assets/Foliage/SpeedTree/Trees/Weeping_Willow/Prefabs/Weeping_Willow_Desktop_101",
    "Assets/Foliage/SpeedTree/Trees/Weeping_Willow/Prefabs/Weeping_Willow_Desktop_102",
    "Assets/Foliage/SpeedTree/Trees/Weeping_Willow/Prefabs/Weeping_Willow_Desktop_Fall101",
    "Assets/Foliage/SpeedTree/Trees/Weeping_Willow/Prefabs/Weeping_Willow_Desktop_Fall102",
    "Assets/Foliage/SpeedTree/Trees/White_Oak/Prefabs/White_Oak_Desktop01",
    "Assets/Foliage/SpeedTree/Trees/White_Oak/Prefabs/White_Oak_Desktop02",
    "Assets/Foliage/SpeedTree/Trees/White_Oak/Prefabs/White_Oak_Desktop03",
    "Assets/Foliage/SpeedTree/Trees/White_Oak/Prefabs/White_Oak_Desktop04",
    "Assets/Foliage/SpeedTree/Trees/White_Oak/Prefabs/White_Oak_Desktop05",
    "Assets/Foliage/SpeedTree/Trees/White_Oak/Prefabs/White_Oak_Desktop_FallA01",
    "Assets/Foliage/SpeedTree/Trees/White_Oak/Prefabs/White_Oak_Desktop_FallB01",
    "Assets/Foliage/SpeedTree/Trees/White_Oak/Prefabs/White_Oak_Desktop_FallB02",
    "Assets/Foliage/SpeedTree8/Trees/Cedar_B_W/Prefabs/Cedar_B_W_001",
    "Assets/Foliage/SpeedTree8/Trees/Cedar_B_W/Prefabs/Cedar_B_W_002",
    "Assets/Foliage/SpeedTree8/Trees/Cedar_B_W/Prefabs/Cedar_B_W_003",
    "Assets/Foliage/SpeedTree8/Trees/Cedar_B_W/Prefabs/Cedar_B_W_004",
    "Assets/Foliage/SpeedTree8/Trees/Cedar_B_W/Prefabs/Cedar_B_W_005",
    "Assets/Foliage/SpeedTree8/Trees/Cedar_B_W/Prefabs/Cedar_B_W_006",
    "Assets/Foliage/SpeedTree8/Trees/Cedar_B_W/Prefabs/Cedar_B_W_007",
    "Assets/Foliage/SpeedTree8/Trees/Cedar_B_W/Prefabs/Cedar_B_W_008",
    "Assets/Foliage/SpeedTree8/Trees/Cedar_B_W/Prefabs/Cedar_B_W_009",  
    "Assets/Foliage/SpeedTree8/Trees/Cedar_B_W/Prefabs/Cedar_B_W_010",
    "Assets/Foliage/SpeedTree8/Trees/Fir_Douglas_B_W/Prefabs/Fir_Douglas_B_W_004",
    "Assets/Foliage/SpeedTree8/Trees/Fir_Douglas_B_W/Prefabs/Fir_Douglas_B_W_008",
    "Assets/Foliage/SpeedTree8/Trees/Fir_Douglas_B_W/Prefabs/Fir_Douglas_B_W_011",
    "Assets/Foliage/SpeedTree8/Trees/Fir_Douglas_B_W/Prefabs/Fir_Douglas_B_W_014",
    "Assets/Foliage/SpeedTree8/Trees/Pine_White_W/Prefabs/Pine_White_W_012",
    "Assets/Foliage/SpeedTree8/Trees/Pine_White_W/Prefabs/Pine_White_W_013",
    "Assets/Foliage/SpeedTree8/Trees/Pine_White_W/Prefabs/Pine_White_W_023",
    "Assets/Foliage/SpeedTree8/Trees/Pine_White_W/Prefabs/Pine_White_W_024",
    "Assets/Foliage/SpeedTree8/Trees/Pine_White_W/Prefabs/Pine_White_W_025",
    "Assets/Foliage/SpeedTree8/Trees/Cherry_Blossom/Prefabs/Cherry_Blossom_001",
    "Assets/Foliage/SpeedTree8/Trees/Cherry_Blossom/Prefabs/Cherry_Blossom_002",
    "Assets/Foliage/SpeedTree8/Trees/Cherry_Blossom/Prefabs/Cherry_Blossom_003",
    "Assets/Foliage/SpeedTree8/Trees/Cherry_Blossom_FA/Prefabs/Cherry_Blossom_FA_001",
    "Assets/Foliage/SpeedTree8/Trees/Cherry_Blossom_FA/Prefabs/Cherry_Blossom_FA_002",
    "Assets/Foliage/SpeedTree8/Trees/Cherry_Blossom_FA/Prefabs/Cherry_Blossom_FA_003",
    "Assets/Foliage/SpeedTree8/Trees/Spruce_Norway/Prefabs/Spruce_Norway_002",
    "Assets/Foliage/SpeedTree8/Trees/Spruce_Norway/Prefabs/Spruce_Norway_004",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Silver/Prefabs/Maple_Silver_005",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Silver/Prefabs/Maple_Silver_009",
    "Assets/Foliage/SpeedTree8/Trees/Wisteria_Pink/Prefabs/Wisteria_Pink_001",
    "Assets/Foliage/SpeedTree8/Trees/Wisteria_Pink/Prefabs/Wisteria_Pink_002",
    "Assets/Foliage/SpeedTree8/Trees/Wisteria_Pink/Prefabs/Wisteria_Pink_003",
    "Assets/Foliage/SpeedTree/Trees/Red_Maple/Prefabs/Red_Maple_Desktop02",
    "Assets/Foliage/SpeedTree/Trees/Red_Maple/Prefabs/Red_Maple_Desktop05",
    "Assets/Foliage/SpeedTree8/Trees/Jungle_B/Prefabs/Jungle_B_005",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Aconitifolium/Prefabs/Maple_Aconitifolium_001",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Aconitifolium/Prefabs/Maple_Aconitifolium_002",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Aconitifolium/Prefabs/Maple_Aconitifolium_003",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Aconitifolium_FA/Prefabs/Maple_Aconitifolium_FA_001",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Aconitifolium_FA/Prefabs/Maple_Aconitifolium_FA_002",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Aconitifolium_FA/Prefabs/Maple_Aconitifolium_FA_003",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Aconitifolium_FB/Prefabs/Maple_Aconitifolium_FB_001",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Aconitifolium_FB/Prefabs/Maple_Aconitifolium_FB_002",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Aconitifolium_FB/Prefabs/Maple_Aconitifolium_FB_003",
    "Assets/Foliage/SpeedTree8/Trees/Myrtle_Crape/Prefabs/Myrtle_Crape_A_001",
    "Assets/Foliage/SpeedTree8/Trees/Myrtle_Crape/Prefabs/Myrtle_Crape_A_003",
    "Assets/Foliage/SpeedTree/Trees/Southern_Live_Oak/Prefabs/SouthernLiveOak_Desktop_Moss06",
    "Assets/Foliage/SpeedTree/Trees/Southern_Live_Oak/Prefabs/SouthernLiveOak_Desktop_Moss10",
    "Assets/Foliage/SpeedTree/Trees/Southern_Live_Oak/Prefabs/SouthernLiveOak_Desktop_Moss11",
    "Assets/Foliage/SpeedTree8/Trees/Pine_Black/Prefabs/Pine_Black_001",
    "Assets/Foliage/SpeedTree8/Trees/Pine_Black/Prefabs/Pine_Black_002",
    "Assets/Foliage/SpeedTree8/Trees/Pine_Black/Prefabs/Pine_Black_003",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Silver/Prefabs/Maple_Silver_011",
    "Assets/Foliage/SpeedTree8/Trees/Wisteria_White/Prefabs/Wisteria_White_001",
    "Assets/Foliage/SpeedTree8/Trees/Wisteria_White/Prefabs/Wisteria_White_002",
    "Assets/Foliage/SpeedTree8/Trees/Wisteria_White/Prefabs/Wisteria_White_003",
    "Assets/Foliage/SpeedTree8/Trees/Wisteria_Purple/Prefabs/Wisteria_Purple_001",
    "Assets/Foliage/SpeedTree8/Trees/Wisteria_Purple/Prefabs/Wisteria_Purple_002",
    "Assets/Foliage/SpeedTree8/Trees/Wisteria_Purple/Prefabs/Wisteria_Purple_003",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Norway/Prefabs/Maple_Norway_004",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Norway/Prefabs/Maple_Norway_001",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Norway/Prefabs/Maple_Norway_002",
    "Assets/Foliage/SpeedTree8/Trees/Maple_Norway/Prefabs/Maple_Norway_003",
    "Assets/Foliage/SpeedTree8/Trees/Birch_Downy/Prefabs/Birch_Downy_003",
    "Assets/Foliage/SpeedTree8/Trees/Birch_Downy/Prefabs/Birch_Downy_002",
    "Assets/Foliage/SpeedTree8/Trees/Birch_Downy/Prefabs/Birch_Downy_001",
    "Assets/Foliage/SpeedTree8/Trees/Birch_Downy/Prefabs/Birch_Downy_007",
    "Assets/Foliage/SpeedTree8/Trees/Birch_Downy/Prefabs/Birch_Downy_006",
    "Assets/Foliage/SpeedTree8/Trees/Birch_Downy/Prefabs/Birch_Downy_005",
    "Assets/Foliage/SpeedTree8/Trees/Birch_Downy/Prefabs/Birch_Downy_004",
    "Assets/Foliage/SpeedTree8/Trees/Larch_European/Prefabs/Larch_European_004",
    "Assets/Foliage/SpeedTree8/Trees/Larch_European/Prefabs/Larch_European_005",
    "Assets/Foliage/SpeedTree8/Trees/Larch_European/Prefabs/Larch_European_002",
    "Assets/Foliage/SpeedTree8/Trees/Larch_European/Prefabs/Larch_European_003",
    "Assets/Foliage/SpeedTree8/Trees/Larch_European/Prefabs/Larch_European_001",
    "Assets/Foliage/SpeedTree/Trees/Lombardy_Poplar/Prefabs/Lombardy_Poplar_Desktop04",
    "Assets/Foliage/SpeedTree8/Trees/Spruce_Norway/Prefabs/Spruce_Norway_009",
    "Assets/Foliage/SpeedTree8/Trees/Spruce_Norway/Prefabs/Spruce_Norway_008",
    "Assets/Foliage/SpeedTree8/Trees/Spruce_Norway/Prefabs/Spruce_Norway_003",
    "Assets/Foliage/SpeedTree8/Trees/Spruce_Norway/Prefabs/Spruce_Norway_001",
    "Assets/Foliage/SpeedTree8/Trees/Spruce_Norway/Prefabs/Spruce_Norway_007",
    "Assets/Foliage/SpeedTree8/Trees/Spruce_Norway/Prefabs/Spruce_Norway_006",
    "Assets/Foliage/SpeedTree8/Trees/Spruce_Norway/Prefabs/Spruce_Norway_005",
    "Assets/Foliage/SpeedTree8/Trees/Pine_Baltic/Prefabs/Pine_Baltic_003",
    "Assets/Foliage/SpeedTree8/Trees/Pine_Baltic/Prefabs/Pine_Baltic_002",
    "Assets/Foliage/SpeedTree8/Trees/Pine_Baltic/Prefabs/Pine_Baltic_001",
    "Assets/Foliage/SpeedTree8/Trees/Pine_Baltic/Prefabs/Pine_Baltic_006",
    "Assets/Foliage/SpeedTree8/Trees/Pine_Baltic/Prefabs/Pine_Baltic_005",
    "Assets/Foliage/SpeedTree8/Trees/Pine_Baltic/Prefabs/Pine_Baltic_004",
    "Assets/Foliage/SpeedTree/Trees/Lombardy_Poplar/Prefabs/Lombardy_Poplar_Desktop07",
    "Assets/Foliage/SpeedTree8/Trees/Spruce_Norway/Prefabs/Spruce_Norway_010",
    "Assets/Foliage/SpeedTree/Trees/Lombardy_Poplar/Prefabs/Lombardy_Poplar_Desktop03"
]

normal_trees_2k = {
    2:  [  0,   1,   2,   5,   6],
    5:  [ 47,  48,  49,  73],
    6:  [ 89,  90,  91,  93,  94,  95,  99, 100],
    7:  [ 15,  16,  17,  21,  22,  50,  51,  61,  62,  63, 116, 117, 120, 121, 122, 123, 124],
    8:  [ 18,  20,  23,  24,  52,  53,  54,  65,  66,  67,  68,  71,  72,  74, 118, 119, 125],
    9:  [ 14,  87,  88],
    10: [  7,   8,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103],
    11: [ 16,  17,  22,  50,  51,  61,  62,  73, 120, 121, 122],
    12: [ 80,  82,  83,  84,  85,  86],
    13: [  0,   1,   2,   3,   4,   6,   7,   8, 101, 102, 103],
    14: [ 18,  19,  23,  24,  50,  53,  54,  65,  74,  81, 126, 127],
    15: [ 16,  17,  50,  51,  61,  64, 123, 124],
    50: [ 73, 147, 148, 149, 150, 151, 152, 155, 156, 157, 158, 159, 160, 162, 163, 
         164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 
         179, 180, 181, 182, 183, 184, 185, 186],
    # Fjordland (theme 54) - broad-canopy / wider forms from the supplied 2K25 reference course
    54: [
          85, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197,
         177, 178, 179
    ]
} 

skinny_trees_2k = {
    2:  [ 28,  29,  30,  31,  33,  34,  35,  37],
    5:  [ 11,  25,  26,  27,  38,  39,  41,  42,  43,  55,  56,  57,  75,  76,  77,  78,  79],
    6:  [ 32,  36, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113],
    7:  [ 69,  70],
    8:  [ 44,  45,  46],
    9:  [ 11,  12, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 
         143, 144, 145, 146],
    10: [ ],
    11: [ 10,  39,  42,  56,  69,  70],
    12: [ 11,  12,  13,  14,  38,  39,  58,  59,  60],
    13: [105, 106, 107, 108, 110, 111, 112, 113, 114, 115],
    14: [ 39,  42],
    15: [  9,  10,  40,  41,  42,  55],
    50: [153, 154, 161],
    # Fjordland (theme 54) - narrow / columnar / conifer forms from the supplied 2K25 reference course
    54: [
         198, 199, 200, 201, 202, 203, 204, 205, 206, 153, 207, 208,
         209, 210, 154,  77,  75,  78,  70,  69, 211, 212, 213, 214,
         215, 216, 217, 218, 219
    ]
} 